### ISSUE TITLE
File name too long: getting the submodules (on MacOS)

### ISSUE THREAD

**Issue by clemens-tolboom** [godot-extended-libraries/godot-tensorflow-workspace#3]
Following https://github.com/godot-extended-libraries/godot-tensorflow-workspace/issues/3#issue-548250651 for #2 I get

```
git submodule update --init --recursive
Submodule 'godot-tensorflow-demo' (https://github.com/godot-extended-libraries/godot-tensorflow-demo.git) registered for path 'godot-tensorflow-demo'
Submodule 'src/godot' (https://github.com/godot-extended-libraries/godot-tensorflow-godot.git) registered for path 'src/godot'
Cloning into '/Users/clemens/Sites/Godot/compile/godot-tensorflow-workspace/godot-tensorflow-demo'...
Cloning into '/Users/clemens/Sites/Godot/compile/godot-tensorflow-workspace/src/godot'...
Submodule path 'godot-tensorflow-demo': checked out '54bb8f09a57c490c69e9484f783dce2b528a0847'
Submodule path 'src/godot': checked out 'd4d5e4025f297dd7430b59a31a596bc3e3ee2823'
Submodule 'modules/tensorflow' (https://github.com/godot-extended-libraries/godot-tensorflow.git) registered for path 'src/godot/modules/tensorflow'
Submodule 'thirdparty/tensorflow' (https://github.com/godot-extended-libraries/tensorflow.git) registered for path 'src/godot/thirdparty/tensorflow'
Cloning into '/Users/clemens/Sites/Godot/compile/godot-tensorflow-workspace/src/godot/modules/tensorflow'...
Cloning into '/Users/clemens/Sites/Godot/compile/godot-tensorflow-workspace/src/godot/thirdparty/tensorflow'...
Submodule path 'src/godot/modules/tensorflow': checked out 'aab52b044dcf954a5474e59825c4c561e695d8b1'
error: unable to create symlink tensorflow/lite/tools/make/downloads/flatbuffers/docs/source/CONTRIBUTING.md: File name too long
Unable to checkout '0ebd265baa4b140aabfef389b764fc07a6578843' in submodule path 'src/godot/thirdparty/tensorflow'
Failed to recurse into submodule path 'src/godot'
```

**Comment by fire** [comment]
Found https://apple.stackexchange.com/questions/86611/does-os-x-enforce-a-maximum-filename-length-or-character-restriction. What git client are you using?

**Comment by clemens-tolboom** [comment]
I had `2.20.1` and upgraded to `2.24.1`

compiling works better now but takes some time.

**Comment by clemens-tolboom** [comment]
Somehow I managed to compile and run your dist of Godot :-)

**Comment by clemens-tolboom** [comment]
This still isn't fixed. iirc I git cloned the tensorflow repo in /tmp then moved it into godot dir.

**Comment by clemens-tolboom** [comment]
Testing with an USB FAT32 failed too. See both https://github.com/godot-extended-libraries/godot-tensorflow-workspace/issues/4#issuecomment-573351174 and https://github.com/godot-extended-libraries/godot-tensorflow-workspace/issues/4#issuecomment-573355386

**Comment by clemens-tolboom** [comment]
Commit 
https://github.com/godot-extended-libraries/tensorflow/commit/993a06ad33a07eee72789ee07a42c2cd98b7ed3a added the files.

and make `download_dependencies.sh` execute https://github.com/godot-extended-libraries/tensorflow/commit/3cb38f5663e740aefa6562cc702bfb26dc3e96d6

I just did ... `download_dependencies.sh` runs

```
  601  git clone git@github.com:tensorflow/tensorflow.git
  602  tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
```

so we probably can make this work by instructing (not working on windows I guess)

```
git clone --recursive git@github.com:godot-extended-libraries/godot-tensorflow-workspace.git
cd godot-tensorflow-workspace
src/godot/thirdparty/tensorflow/tensorflow/lite/tools/make/download_dependencies.sh
```

**Comment by clemens-tolboom** [comment]
Testing for https://github.com/godotengine/godot-docs/pull/3055 the compile included tensorflow

I can run

```
src/godot/bin/godot.osx.tools.64 --editor
src/godot/bin/godot.osx.tools.64 --editor --path ./godot-tensorflow-demo/
```

So for some weird reasons (to much balls in the air / user error ?) the demo runs.
